apiVersion: v1
kind: Service
metadata: 
  name: flask-api
spec:
  type: NodePort
  selector:
    backend: backendpython
  ports:
    - port: 5000 
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: flask-api-cluster
  labels:
    backend: backendpython
spec:
  selector:
    backend: backendpython
  ports:
    - port: 5000 
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-python
  labels:
    backend: backendpython
spec:
  selector:
    matchLabels:
      backend: backendpython
  replicas: 3
  template:
    metadata:
      labels:
        backend: backendpython
    spec:
      containers:
      - name: pythonbackend
        image: redacre/backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
