apiVersion: v1
kind: Service
metadata:  
  name: nodeport-nodejs
  labels:
    web: reactclient
spec:
  type: NodePort
  selector:
    web: reactclient
  ports:  
  - name: http
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - port: 8080
      targetPort: 3000
  type: LoadBalancer
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    web: reactclient
spec:
  replicas: 2
  selector:
    matchLabels:
      web: reactclient
  template:
    metadata:
      labels:
        web: reactclient 
    spec:
      containers:
      - name: nodejs
        imagePullPolicy: Never
        image: "redacre/frontend:latest"
        ports:
        - containerPort: 3000
